# Generated by Django 3.1.7 on 2021-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_billbreakdown_breakdownitem_images_roundup'),
    ]

    operations = [
        migrations.AddField(
            model_name='billbreakdown',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='billbreakdown',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='breakdownitem',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
