# Generated by Django 3.1.7 on 2021-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_billbreakdown_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='billbreakdown',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
