# Generated by Django 3.1.7 on 2021-04-25 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_billbreakdown_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundup',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Wastebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(db_index=True, max_length=200)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Image')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastebook', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
